# Generated by Django 3.1.7 on 2021-05-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_otpdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otpdata',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='userpoint',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
