# Generated by Django 3.1.7 on 2021-05-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210508_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usenums',
            field=models.IntegerField(default=0),
        ),
    ]
