# Generated by Django 3.2.4 on 2021-06-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_usenums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otpdata',
        ),
        migrations.AddField(
            model_name='user',
            name='phonenum',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
