# Generated by Django 3.2.4 on 2021-06-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210613_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(default=0, max_length=100)),
                ('pswd', models.CharField(default=0, max_length=20)),
                ('phonenum', models.IntegerField(default=0, max_length=20)),
            ],
        ),
    ]
