# Generated by Django 3.2.4 on 2021-06-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
